package com.almundo.callcenter.model;

import model.Llamada;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

/**
 * Test de la clase Llamada
 *
 * @author Leonardo
 */
public class LlamadaTest {

    @Before
    public void setUp() {
        //Iniciar el generador de id en 0
        Llamada.count.set(0);
    }

    @Test
    public void shouldInstantiateOneObjectWithAutogeneratedId() {
        Llamada llamada = new Llamada();
        Assert.assertEquals(1, llamada.getId());
    }

    @Test
    public void shouldInstantiateTenObjectsWithAutogeneratedId() {
        List<Llamada> llamadas = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            llamadas.add(new Llamada());
        }
        Assert.assertEquals(10, llamadas.size());
        Assert.assertEquals(10, llamadas.get(9).getId());
    }

}
